### ISSUE TITLE
Tensorflow frozen file

### ISSUE THREAD

**Issue by prnvjb** [shamangary/FSA-Net#10]
Hi,
I'm trying to convert your keras models to tensorflow frozen ('*.pb') model but unsuccessful. Could you please provide me a direction to convert them to frozen models? The pretrained models you provided doesn't contain config and when I tried to save them I'm getting few errors and unable to rectify them.
Thanks!!

**Comment by shamangary** [comment]
Hello @prnvjb, I think it's not a good idea to assume there is an easy way to convert the whole model since there are a lot of customized layers. Therefore, I would recommend rewriting the whole thing and train it again.

**Comment by prnvjb** [comment]
Thanks @shamangary  , I'll try it.
