### ISSUE TITLE
Data download

### ISSUE THREAD

**Issue by QingL0218** [shamangary/FSA-Net#12]
Hi shamangary,because of the VPN problem, I can't open the data download url on Google Driver, could you give another link,please? THX

**Comment by shamangary** [comment]
Hello. Is dropbox ok for you?

**Comment by QingL0218** [comment]
sorry, it doesn't ok

**Comment by shamangary** [comment]
Sorry that's all I have. I have to suggest you re-run the pre-processing by downloading the datasets.

**Comment by Maxwell2017** [comment]
> Hi shamangary,because of the VPN problem, I can't open the data download url on Google Driver, could you give another link,please? THX

I have the same question about vpn. Have you downloaded  these datasets now?

**Comment by QingL0218** [comment]
@Maxwell2017 you can use Hoxx to download
