### ISSUE TITLE
Visualizations of the discovered fine-grained spatial structures

### ISSUE THREAD

**Issue by zjz19960805** [shamangary/FSA-Net#13]
excuse me.
In the 4.6 sessions of your paper,  you have introduced some heatmap about the attention of each row vector of Mk to the input image.
I wonder how the row vector of Mk can generate the heatmap. Because the shape of each row of Mk is (w*h*K), but the shape of the heatmap is (64*64*3).
Have you used upsampling or deconvolution?
Thanks!

**Comment by shamangary** [comment]
Hello @zjz19960805,

The projection M_k in the paper is corresponding to SR_matrix (https://github.com/shamangary/FSA-Net/blob/master/training_and_testing/FSANET_model.py#L771).

The dimension is (m_dim, 64x3) with (w x h) = 64 and K=3.
For m_dim = 0 and a single-stage K,  (w x h) can be seen as the heatmap we presented in our paper.
It can be upscale by some trick such as bilinear interpolation and overlap with the original input image.

**Comment by zjz19960805** [comment]
thanks for your reply, it works for me.
another question, please~
in your paper, you have used a two-stream-network which is similar to the DeepCD and SSR-Net, and I think it is a kind of patch descriptor, right? and it always used for image matching.
so why you use it, and what is the differences between the feature extracted from it and the feature extracted from ResNet50 used by HopeNet? Because I think the depth of the two networks is very different.
thanks again~

**Comment by shamangary** [comment]
Because we discover two-stream structure can be adopted in very different situations and still acquire good performance. (patch, age, action recognition,... ) Therefore, we believe it's worth study in two-stream structure rather than just follow traditional Resnet. Everyone doing the same thing is kind of boring :D .
