### ISSUE TITLE
Question about training image normalization 

### ISSUE THREAD

**Issue by janicevidal** [shamangary/FSA-Net#15]
How to pre-process normalization on the training and testing image， I can not find relate code. But , in demo_FSANET_mtcnn.py,  find
 `cv2.normalize(faces[i,:,:,:], None, alpha=0, beta=255, norm_type=cv2.NORM_MINMAX) `

**Comment by shamangary** [comment]
Hello @janicevidal, during training, we just make sure the image intensity range is bewteen [0,255]. In keras training, there is no big difference to normalize it to [0,1] (at least in my experiment there is no obivious effect.)

**Comment by janicevidal** [comment]
> Hello @janicevidal, during training, we just make sure the image intensity range is bewteen [0,255]. In keras training, there is no big difference to normalize it to [0,1] (at least in my experiment there is no obivious effect.)

**Comment by janicevidal** [comment]
@shamangary Thanks
