### ISSUE TITLE
Question regarding SSR-Net models

### ISSUE THREAD

**Issue by MoltenMuffins** [shamangary/FSA-Net#16]
Firstly, thanks for sharing your work with us!

My question is as follows: 
There are multiple classes of SSR-Net defined in FSANET_model.py.
- SSR_net
- SSR_net_general
- SSR_net_MT
- SSR_net_ori_MT

I understand that SSR_net is for the age regression problem, but what is the general difference between SSR_net_general, SSR_net_MT and SSR_net_ori_MT? Which one was used to compare results in the paper (SSR-Net-MD)?

**Comment by shamangary** [comment]
Hello. In the paper, MD means multiple dimension. In the code, I wrote MT as multi-task which is corresponding to 3 output (yaw, pitch, roll). But they are the same thing.

As for the SSR_net_MT and SSR_net_ori_MT, we use new two-stream structure (including seperable convolution layer) for the first one, and the original '[IJCAI18] SSR-Net' two-stream structure is adopted in the SSR_net_ori_MT.

SSR_net_general just a model I want to try on different regression problem which you may ignore.

**Comment by MoltenMuffins** [comment]
Thanks for the explanation! May I also ask what the variable `lambda_d` represents in the model code?

**Comment by shamangary** [comment]
It’s the hyperparameter for controlling the dynamic scaling in SSR module. I set it to 1 and no further tuning is needed

**Comment by MoltenMuffins** [comment]
Thanks for taking the time to answer my queries!
