### ISSUE TITLE
Question about the code of demo_FSANET_mtcnn.py

### ISSUE THREAD

**Issue by Keiku** [shamangary/FSA-Net#19]
I'm reading `FSA-Net/demo/demo_FSANET_mtcnn.py` now, but I have some questions, so let me ask a question. What is the parameter `ad` ? Also why do you need `detected_pre` ?

**Comment by shamangary** [comment]
Hello @Keiku,
ad means additional margin. Basically we enlarge the size of the detected face region for capturing the context.

Sometimes the detection would fail but the head is still at a similar spot, therefore we can use detected_pre as the detected region based on the previous frame.
