### ISSUE TITLE
Image normalization during training and testing

### ISSUE THREAD

**Issue by ksachdeva** [shamangary/FSA-Net#23]
Hi @shamangary 

I could not find (figure out) where you do image normalization (either per image standardization and/or bring the images to center using some predefined mean & std).

Regards
Kapil

**Comment by shamangary** [comment]
Hello @ksachdeva, you couldn't find it because there is no such thing. I use the normalization before and without. It turns out there is no obvious difference. I know the theory told us that there should be one, but the practical results show it's case dependent.

**Comment by ksachdeva** [comment]
ok. makes sense then. thanks for the clarification.
