### ISSUE TITLE
About detection efficiency

### ISSUE THREAD

**Issue by RomanticWithoutStatus** [shamangary/FSA-Net#27]
Hi，how long does FSA-Net take to detect a picture，in python or c++

**Comment by shamangary** [comment]
Hello @RomanticWithoutStatus,
There are two part of the estimation pipeline: (1) face detection (2) pose estimation

For my ssd+ FSA-Net demo code, the following time cost is shown below
```
detection time: 0.017 secs
pred time:0.016 secs
```

**Comment by RomanticWithoutStatus** [comment]
> Hello @RomanticWithoutStatus,
> There are two part of the estimation pipeline: (1) face detection (2) pose estimation
> 
> For my ssd+ FSA-Net demo code, the following time cost is shown below
> 
> ```
> detection time: 0.017 secs
> pred time:0.016 secs
> ```

And what are your GPU and CPU models

**Comment by shamangary** [comment]
Intel i7 8th gen
GTX1060
Acer laptop

**Comment by shamangary** [comment]
I assume SSR_net_MT is the shortest one because it's the simplest.

**Comment by RomanticWithoutStatus** [comment]
> I assume SSR_net_MT is the shortest one because it's the simplest.

thank you

**Comment by Maxwell2017** [comment]
> Hello @RomanticWithoutStatus,
> There are two part of the estimation pipeline: (1) face detection (2) pose estimation
> 
> For my ssd+ FSA-Net demo code, the following time cost is shown below
> 
> ```
> detection time: 0.017 secs
> pred time:0.016 secs
> ```

Hi shamangary, I have a question about speed. In your article, I found that the inference time of model is 1ms  per image，is that run with lbp?

**Comment by shamangary** [comment]
It was with my PC with SSD, the face detection time is not included. I have no access to that computer now.

**Comment by Maxwell2017** [comment]
> It was with my PC with SSD, the face detection time is not included. I have no access to that computer now.

This is my hardware device：
GPU: GTX 1080ti
CPU: Intel(R) Core(TM) CPU i7-8700K @ 3.70GHz

i don't think the inference time is limited with ssd, moreover, My hardware is basically the same as yours，so confused:(

**Comment by Reddyforcode** [comment]
@Maxwell2017 did you check if while the inference is being done, the gpu is handing this process? you can check it whit "nvidia-smi" on the console

**Comment by Maxwell2017** [comment]
@Reddyforcode of course, i have checked that, and the gpu utilization ratio is around 40%.Have you reproduced the speed? thx

**Comment by shamangary** [comment]
By SSD, I meant Solid-State Drive. If you want to compare the efficiency, just recalculate it on your own device and it would be fair.

**Comment by Maxwell2017** [comment]
@shamangary @Reddyforcode what I'm confused about is that the SSD is the hard disk, isn't the model prediction of keras only performed on GPU?

**Comment by shamangary** [comment]
@Maxwell2017 I originally have the same question as you do, and someday I just try it and it's somehow much much faster.
