### ISSUE TITLE
[OpenVINO] How to convert to OpenVino with the freezed graph

### ISSUE THREAD

**Issue by leviethung2103** [shamangary/FSA-Net#33]
Hi Kapil Sachdeva, 

I've seen your code that converts the kera model into *pb tensorflow model. I really want to test the converted model into openvino because I have a edge device and then test the real performance on that. 

However, I am not familiar with Model Graph. Could you please give me some suggestions about converting tensorflow model into OpenVINO model. Is that possible or not? 

I've counted many problems that related with input_shape of graph. 

Thank you in advanced.

**Comment by shamangary** [comment]
Kapil Sachdeva is not the official maintainer of this repo. Asking him to solve the issue of this repo is not appropriate.

**Comment by leviethung2103** [comment]
I am really sorry about that. I saw that Kapil Sachdeva contributed the conversion file from keras to tensorflow. I was struggling with converting Tensorflow to Openvino. Could you please help me figure out the problem? I am really appriciate that.

**Comment by leviethung2103** [comment]
I've figured out the problem.
