### ISSUE TITLE
Inference time

### ISSUE THREAD

**Issue by KamalM8** [shamangary/FSA-Net#35]
Hi, 
Thank you for uploading the implementation of your seminal work on head pose estimation. I am having issues determining the time taken for a single forward pass of an image. In the paper, it is explicitly stated that an image takes 1 ms for inference using a 1080 TI GPU. I have the same hardware and a forward pass takes 16 ms which is approximately 10 times slower than what was mentioned. This is how I measured time:

`start = time.time()`
`p_result = model.predict()`
`end = time.time()`
`time_taken = end - start`

I would appreciate if you could clear this up for me. 
Thanks

**Comment by shamangary** [comment]
Hello, the inference time also depends on the drive such as different kinds of SSD, but the result you are getting is normal.
