### ISSUE TITLE
Some questions about SSR-Net.

### ISSUE THREAD

**Issue by CrossEntropy** [shamangary/FSA-Net#43]
Hi, @shamangary Thank you for your contribution in the paper.

I found some problems while reading the code `SSRNET_model.py`.

Quesion 1:
  In `class SSR_net_ori_MT:`
  ``` s_layer4 = Conv2D(64,(1,1),activation='tanh')(s_layer4)
       s_layer4 = MaxPooling2D((2,2))(s_layer4)

       x_layer4 = Conv2D(64,(1,1),activation='relu')(x_layer4)
       x_layer4 = AveragePooling2D((2,2))(x_layer4)

       feat_s1_pre = Multiply()([s_layer4,x_layer4])
       feat_s1_pre = Flatten()(feat_s1_pre)
  ```
Why should the output of the last layer be used as the input of stage one, shouldn't the output of the first layer be used as the input of stage one?

Question 2:
 In `class SSR_net_ori_MT:`
 ```# Classifier block
        s_layer4 = Conv2D(64,(1,1),activation='tanh')(s_layer4)
        s_layer4 = MaxPooling2D((2,2))(s_layer4)

        x_layer4 = Conv2D(64,(1,1),activation='relu')(x_layer4)
        x_layer4 = AveragePooling2D((2,2))(x_layer4)

        feat_s1_pre = Multiply()([s_layer4,x_layer4])
        feat_s1_pre = Flatten()(feat_s1_pre)
        feat_delta_s1 = Dense(2*self.num_classes,activation='tanh')(feat_s1_pre)
        delta_s1 = Dense(self.num_classes,activation='tanh',name='delta_s1')(feat_delta_s1)

        feat_local_s1 = Dense(2*self.num_classes,activation='tanh')(feat_s1_pre)
        local_s1 = Dense(units=self.num_classes, activation='tanh', name='local_delta_stage1')(feat_local_s1)

        feat_pred_s1 = Dense(self.stage_num[0]*self.num_classes,activation='relu')(feat_s1_pre) 
        pred_a_s1 = Reshape((self.num_classes,self.stage_num[0]))(feat_pred_s1)
```
   Why the numbers of  `local_s1`  is `self.num_classes`, not `self.num_classes *self.stage_num[0]`? 

Question 3:
  In `class SSR_net_ori_MT:`
  ```def SSR_module(x,s1,s2,s3,lambda_d):
            a = x[0][:,:,0]*0
            b = x[0][:,:,0]*0
            c = x[0][:,:,0]*0

            di = s1//2
            dj = s2//2
            dk = s3//2

            V = 99
            #lambda_d = 0.9

            for i in range(0,s1):
                a = a+(i-di+x[6])*x[0][:,:,i]
            # a = K.expand_dims(a,-1)
            a = a/(s1*(1+lambda_d*x[3]))

            for j in range(0,s2):
                b = b+(j-dj+x[7])*x[1][:,:,j]
            # b = K.expand_dims(b,-1)
            b = b/(s1*(1+lambda_d*x[3]))/(s2*(1+lambda_d*x[4]))

            for k in range(0,s3):
                c = c+(k-dk+x[8])*x[2][:,:,k]
            # c = K.expand_dims(c,-1)
            c = c/(s1*(1+lambda_d*x[3]))/(s2*(1+lambda_d*x[4]))/(s3*(1+lambda_d*x[5]))

            pred = (a+b+c)*V
       
            return pred
 ```
 As far as I know, the range of the angle is -99 ~ 99. How can I ensure that I get a negative angle?
 Why `V` is 99?

**Comment by shamangary** [comment]
Hello @CrossEntropy,

Thank you for your appreciation.
Q1: The idea of this is based on the low-level information is very delicate and the semantic information is usually at the deeper layer. Therefore I designed the deepest layer as the 1st stage.
However, FSA-Net is trying to resolve that manual design problem by learning the aggregation instead of assigning by human design. 

Q2:Just empirical choice. No deep explanation.

Q3:Since there is di, dj, dk, the indices are shifted from [0,1,2] to [-1,0,1]. Therefore you may get negative value. The choice of V is just the limit of the prediction. No deep explanation.

**Comment by CrossEntropy** [comment]
Thanks for your help! @shamangary
