### ISSUE TITLE
Roll-Yaw-Pitch left-handed coordinate

### ISSUE THREAD

**Issue by daniellee8527** [shamangary/FSA-Net#47]
Nice work !
But I still  have some question about the output values : 
What is the original coordinate before you print out the value of roll-yaw-pitch ? Because I saw that you gave the "yaw" a minus signal to draw the axis of head, and I try to use your results in my robot, but when I do the coordinate transference, I encountered some problem. I want to know is the output roll-yaw-pitch is represent to the axis drawn on the output image and based on left-handed coordinate or it is already in right-handed coordinate system. 
I used webcam as the input, and the coordinate of webcam is X toward right, Y toward down and Z toward in the screen, take your result image for example, how can I do the coordinate transference, could you give me some advises?

**Comment by Baoste** [comment]
hello, did you solve this problem?
