### ISSUE TITLE
training about baseline 'Hopenet'?

### ISSUE THREAD

**Issue by maliho0803** [shamangary/FSA-Net#5]
did you training Hopenet by yourself using 300W-LP? if so ,what is your training parameters?

**Comment by shamangary** [comment]
Hello. I simply take the pre-trained model from hopenet's github. The training process of this repository also follows their paper and code. Therefore, it is trained on 300W-LP.

**Comment by yxdforever** [comment]
When you use 300W_LP training, have you sampled and blurred the data set in the way of hopenet?

**Comment by shamangary** [comment]
Hello @yxdforever, our training augmentation is just cropping. No complex augmentation is adopted. But you are free to try them and ideally it would be better (maybe?
