### ISSUE TITLE
where to get synhead_noBIWI.npz

### ISSUE THREAD

**Issue by gneworld** [shamangary/FSA-Net#51]
hello, thanks for your great job. I don't find synhead_noBIWI.npz in your supplied data url, so  where should I to get  synhead_noBIWI.npz file?  thanks much

**Comment by shamangary** [comment]
Hello. It was not implemented. But you may do the same preprocessing with SynHead https://docs.google.com/forms/d/e/1FAIpQLSe6EP2FznQmlIf-QP8VJ638p9Da4wiZz2u-iTGtDgWV0qzXOA/viewform

**Comment by gneworld** [comment]
thanks very much
