### ISSUE TITLE
Is there any problem if I set the batch_size as 64 or 128.

### ISSUE THREAD

**Issue by jake221** [shamangary/FSA-Net#6]
Is there any problem if I set the batch_size as 64 or 128? Because I have two GPU (P100, 16GB), so I want to increase the training speed to save time. But I want to know if this would drop the accuracy. Thanks for your reply.

**Comment by shamangary** [comment]
Hello @jake221, I never try that actually, but I think the original training process is fast enough. If you make the batch_size even larger, it will be very fast and you can basically try everything :D

**Comment by jake221** [comment]
thanks for your reply. I will try! Best

**Comment by jake221** [comment]
> Hello @jake221, I never try that actually, but I think the original training process is fast enough. If you make the batch_size even larger, it will be very fast and you can basically try everything :D

Hello, @shamangary, I try to load the model I trained myself. However, it report an error

  File "demo_fsanet.py", line 67, in model_init
    fsa_model = load_fsanet()
  File "demo_fsanet.py", line 49, in load_fsanet
    model1.load_weights(weight_file1)
  File "D:\Users\w00440748\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\engine\network.py", line 1166, in load_weights
    f, self.layers, reshape=reshape)
  File "D:\Users\w00440748\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\engine\saving.py", line 1030, in load_weights_from_hdf5_group
    str(len(filtered_layers)) + ' layers.')
ValueError: You are trying to load a weight file containing 1 layers into a model with 4 layers.

**Comment by shamangary** [comment]
Hello @jake221,
The error shows
```
ValueError: You are trying to load a weight file containing 1 layers into a model with 4 layers.
```
There are three models:

model1 = FSA_net_Capsule(image_size, num_classes, stage_num, lambda_d, S_set)()
model2 = FSA_net_Var_Capsule(image_size, num_classes, stage_num, lambda_d, S_set)()
model3 = FSA_net_noS_Capsule(image_size, num_classes, stage_num, lambda_d, S_set)()

Can you check that the loading weight is correctly corresponding to the right model type?
It seems possible that you are loading the weight of FSA_net_noS_Capsule into other two model structure.

**Comment by jake221** [comment]
> Hello @jake221,
> The error shows
> 
> ```
> ValueError: You are trying to load a weight file containing 1 layers into a model with 4 layers.
> ```
> 
> There are three models:
> 
> model1 = FSA_net_Capsule(image_size, num_classes, stage_num, lambda_d, S_set)()
> model2 = FSA_net_Var_Capsule(image_size, num_classes, stage_num, lambda_d, S_set)()
> model3 = FSA_net_noS_Capsule(image_size, num_classes, stage_num, lambda_d, S_set)()
> 
> Can you check that the loading weight is correctly corresponding to the right model type?
> It seems possible that you are loading the weight of FSA_net_noS_Capsule into other two model structure.

No, I am pretty sure I didnot make that mistake. I just replace the model I trained myself as the models you provide, it worked. There are some similar errors for Keras. But they didnot work for me.
https://www.jianshu.com/p/e76f56992b65
https://github.com/keras-team/keras/issues/11072

**Comment by shamangary** [comment]
https://github.com/keras-team/keras/issues/10417

It seems that keras 2.2.2 could cause such problem when the model uses InputeLayer.
Can you try to downgrade the keras version? 2.1.0 or 2.0.0?
