### ISSUE TITLE
what is the di dj dk means ?

### ISSUE THREAD

**Issue by TemiLee** [shamangary/FSA-Net#7]
good job! thanks for your work!
I’m confused in this code in your FASNET_model.py，why the di = s1//2 ? what is this meaning?
and i'm not find it in your paper

`     
   
           def SSR_module(x,s1,s2,s3,lambda_d):
            
            a = x[0][:,:,0]*0
            b = x[0][:,:,0]*0
            c = x[0][:,:,0]*0

            di = s1//2
            dj = s2//2
            dk = s3//2

            V = 99
            #lambda_d = 0.9

            for i in range(0,s1):
                a = a+(i-di+x[6])*x[0][:,:,i]
            a = a/(s1*(1+lambda_d*x[3]))

            for j in range(0,s2):
                b = b+(j-dj+x[7])*x[1][:,:,j]
            b = b/(s1*(1+lambda_d*x[3]))/(s2*(1+lambda_d*x[4]))

            for k in range(0,s3):
                c = c+(k-dk+x[8])*x[2][:,:,k]
            c = c/(s1*(1+lambda_d*x[3]))/(s2*(1+lambda_d*x[4]))/(s3*(1+lambda_d*x[5]))

            pred = (a+b+c)*V
            
            return pred
`

**Comment by shamangary** [comment]
Hello @TemiLee, it is because of the nature of the angles which can be positive or negative. (di,dj,dk) are just some fixed parameter to switch the range of index "i in [0,s1]" into "i in [-s1//2,s1//2]"
