### ISSUE TITLE
The code's Normalization different with paper?

### ISSUE THREAD

**Issue by TemiLee** [shamangary/FSA-Net#8]
In your code the normalization is use the K.sum :
```
# Very important!!! Without this training won't converge.
# norm_S = Lambda(lambda x: K.tile(K.sum(x,axis=-1,keepdims=True),(1,1,64)))(S_matrix)
norm_S_s1 = Lambda(lambda x: K.tile(K.sum(x,axis=-1,keepdims=True),(1,1,64)))(S_matrix_s1)
norm_S_s2 = Lambda(lambda x: K.tile(K.sum(x,axis=-1,keepdims=True),(1,1,64)))(S_matrix_s2)
norm_S_s3 = Lambda(lambda x: K.tile(K.sum(x,axis=-1,keepdims=True),(1,1,64)))(S_matrix_s3)

```
But in your paper section3.5:

> L1 normamlization is performed for each row of Sk for more stable training

why there have the different ? Does this include deeper considerations?

**Comment by TemiLee** [comment]
I mean L1 normalization contains 'absolute values' ​​and 'adds'  two operations,But K.sum is only add not to take absolute value

**Comment by shamangary** [comment]
Hello @TemiLee, you are really reading it very carefully XDDDDDDD

The S_matrix is the fine-grained projection matrix for mapping the feature. Note that I add sigmoid as the activation on the S_matrix before this normalization. So the sum is equal to the L1-norm.

**Comment by TemiLee** [comment]
@shamangary understood ， thanks
