### ISSUE TITLE
tflite

### ISSUE THREAD

**Issue by TemiLee** [shamangary/FSA-Net#9]
Hi Have you tried to convert the model file to tflite?  I'm tried this but failed.

**Comment by shamangary** [comment]
There are a lot of custom layers, so I guess it will need some special treatment. However, it's not in our plan now.

**Comment by HansonSun** [comment]
i also encountered this issue, at least,  hope to have a tensorflow or pytorch version code, thanks

**Comment by tatevmejunts** [comment]
Hello everyone. Has anyone converted model to tflite? @TemiLee @HansonSun
